export interface TestimonialStory {
  slug: string;
  name: string;
  location: string;
  locationCode: string;
  videoId: string;
  headlineLead: string;
  headlineOutline: string;
  headlineClose: string;
  primaryQuote: string;
  secondaryQuote: string;
}

export const TESTIMONIAL_STORIES: TestimonialStory[] = [
  {
    slug: "melissa",
    name: "Melissa",
    location: "Tennessee",
    locationCode: "TN",
    videoId: "BbpXNx7Jixo",
    headlineLead: "THE BEST",
    headlineOutline: "CONFERENCE",
    headlineClose: "OF MY LIFE.",
    primaryQuote: "It literally was like no conference I’ve ever been to and totally life-changing.",
    secondaryQuote: "I cannot wait to attend next year and bring my staff.",
  },
  {
    slug: "kelly",
    name: "Kelly",
    location: "Pennsylvania",
    locationCode: "PA",
    videoId: "qnjwHng6MZ0",
    headlineLead: "YOU NEED TO",
    headlineOutline: "BE THERE",
    headlineClose: "IN PERSON.",
    primaryQuote: "You really need to be in person to see it, experience it, and take it all in.",
    secondaryQuote: "It’s not like any other event you’ve ever been to.",
  },
  {
    slug: "anthony",
    name: "Anthony",
    location: "Virginia",
    locationCode: "VA",
    videoId: "nxEutmCrBm0",
    headlineLead: "AUTHENTIC.",
    headlineOutline: "RAW.",
    headlineClose: "GENUINE.",
    primaryQuote: "Formula was authentic. It was raw. It was genuine.",
    secondaryQuote: "You gave us something unlike any other conference before.",
  },
  {
    slug: "jay",
    name: "Jay",
    location: "Florida",
    locationCode: "FL",
    videoId: "wvutVhMg-zM",
    headlineLead: "THIS IS",
    headlineOutline: "A MUST",
    headlineClose: "FOR OWNERS.",
    primaryQuote: "If you’re an agency owner, this is a must.",
    secondaryQuote: "I have two takeaways right away to get back and start executing in my agency.",
  },
  {
    slug: "cody",
    name: "Cody",
    location: "Texas",
    locationCode: "TX",
    videoId: "RRBQd4dQJo0",
    headlineLead: "KNOCKED IT",
    headlineOutline: "OUT OF",
    headlineClose: "THE PARK.",
    primaryQuote: "You knocked this thing out of the park.",
    secondaryQuote: "I got more notes than I’ve ever had from a conference.",
  },
  {
    slug: "romilee",
    name: "Romilee",
    location: "Louisiana",
    locationCode: "LA",
    videoId: "SR_9T5S6BeI",
    headlineLead: "THE RIGHT",
    headlineOutline: "SPACE",
    headlineClose: "FOR MY TEAM.",
    primaryQuote: "It’s one of the best things I ever did as an agency owner.",
    secondaryQuote: "We loved how it was actionable—tactical actions we can implement right away.",
  },
  {
    slug: "john",
    name: "John",
    location: "Florida",
    locationCode: "FL",
    videoId: "-58mxGklI8k",
    headlineLead: "CHANGE YOUR",
    headlineOutline: "PERSON.",
    headlineClose: "CHANGE BUSINESS.",
    primaryQuote: "Change your person, change your life, change your business.",
    secondaryQuote: "Formula Forum 2025 was like nothing I’ve ever been to.",
  },
  {
    slug: "kim",
    name: "Kim",
    location: "Florida",
    locationCode: "FL",
    videoId: "g0lNoUA6V04",
    headlineLead: "ACTIONABLE",
    headlineOutline: "IDEAS.",
    headlineClose: "IMMEDIATE IMPACT.",
    primaryQuote: "I think we walked away with perfect actionable ideas to immediately implement into our agencies.",
    secondaryQuote: "It was the first conference I’ve been to where I felt like everyone was outside of their comfort zones in the best possible way.",
  },
  {
    slug: "mike",
    name: "Mike",
    location: "Florida",
    locationCode: "FL",
    videoId: "Z43PeAOFQyw",
    headlineLead: "NEW IDEAS.",
    headlineOutline: "REAL",
    headlineClose: "CONNECTIONS.",
    primaryQuote: "It was great connecting with high achievers. Everyone there really wants to take their agencies to the next level.",
    secondaryQuote: "The breakout sessions were something definitely different and well thought out.",
  },
  {
    slug: "steve",
    name: "Steve",
    location: "Maine",
    locationCode: "ME",
    videoId: "N-FFSaNgkXw",
    headlineLead: "CLARITY.",
    headlineOutline: "CONFIDENCE.",
    headlineClose: "GROWTH.",
    primaryQuote: "It will challenge you. It will inspire you, and it will give you the clarity and confidence to elevate both your business and, more importantly, yourself.",
    secondaryQuote: "This forum cuts through that noise and equips you not only with practical tools for success, but also the mindset and self-awareness to use them with deliberate purpose.",
  },
  {
    slug: "ladd",
    name: "Ladd",
    location: "Florida",
    locationCode: "FL",
    videoId: "KieUmx_iC-c",
    headlineLead: "THE MOST",
    headlineOutline: "IMPACTFUL",
    headlineClose: "CONFERENCE.",
    primaryQuote: "That was the most impactful conference I’ve ever been to.",
    secondaryQuote: "My team members were absolutely floored with the presentations and the message.",
  },
  {
    slug: "lisa",
    name: "Lisa",
    location: "Florida",
    locationCode: "FL",
    videoId: "Y_l0ivxt8zg",
    headlineLead: "WORK ON",
    headlineOutline: "YOURSELF",
    headlineClose: "FIRST.",
    primaryQuote: "It encourages you to work on yourself first.",
    secondaryQuote: "These two together put their heart and soul into a conference that really was beyond amazing.",
  },
  {
    slug: "sean",
    name: "Sean",
    location: "Florida",
    locationCode: "FL",
    videoId: "5Em3NPtlTUs",
    headlineLead: "BRING",
    headlineOutline: "MORE",
    headlineClose: "OF YOUR TEAM.",
    primaryQuote: "My only regret is that I wish I would have brought more of my team members to the event.",
    secondaryQuote: "I took a ton of notes on that process, which we definitely plan on implementing when we get back.",
  },
  {
    slug: "jeff",
    name: "Jeff",
    location: "Florida",
    locationCode: "FL",
    videoId: "NOLMVH50QYM",
    headlineLead: "THE",
    headlineOutline: "MENTAL",
    headlineClose: "EDGE MATTERS.",
    primaryQuote: "Are you mentally prepared to do what you have to do to be successful?",
    secondaryQuote: "I love that this conference really focused on that, making sure that you were ready and committed to do whatever it’s going to take.",
  },
  {
    slug: "craig",
    name: "Craig",
    location: "Florida",
    locationCode: "FL",
    videoId: "jazyZ8OoX8w",
    headlineLead: "A",
    headlineOutline: "GAME",
    headlineClose: "CHANGER.",
    primaryQuote: "Great energy, great people, powerful takeaways.",
    secondaryQuote: "If you haven’t registered for next year, you won’t want to miss it. It’s a game changer.",
  },
];

export const getTestimonialStory = (slug: string | undefined) =>
  TESTIMONIAL_STORIES.find((story) => story.slug === slug);
