// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byoxxlouggcvbdizhgdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5b3h4bG91Z2djdmJkaXpoZ2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjAzNTEsImV4cCI6MjA3MDgzNjM1MX0.yIr4_LGwLJpBSPYXbWjXo8nPrwuBcoGLkT3JJB434oQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});